### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by digitalit** [keeross/adonis-starter#1]
Hi,
Great starter.
just wondering, why less and not sass? and what is all babel stuff is it necessary?

Great work, thank you.

**Comment by keeross** [comment]
You can easily switch to SASS. I personally don't see any great difference between LESS or SASS/SCSS, maybe a little bit in terms of performance.
Babel is needed to compile ES2015 stuff to legacy javascript but again, you may disable it.
But yes, for the most part of present browsers there is no need in it.
https://kangax.github.io/compat-table/es6/

**Comment by digitalit** [comment]
Ok, thank you.
